# Generated by Django 5.1 on 2024-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
