# Generated by Django 5.1 on 2024-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'up_votes'), (-1, 'down_votes')], default=0),
        ),
    ]
