# Generated by Django 5.1 on 2024-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_customtext_down_votes_customtext_up_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSED')], default=0),
        ),
    ]
