# Generated by Django 5.1 on 2024-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_curriculum_required_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='program_code',
            field=models.CharField(default='CENG', max_length=100),
            preserve_default=False,
        ),
    ]
