# Generated by Django 5.1.1 on 2024-10-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_curriculumcoursesemester_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdream',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='academicdream',
            name='courses',
        ),
        migrations.AddField(
            model_name='academicdream',
            name='CurriculumCourseSemester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.curriculumcoursesemester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='givencoursesandthesemestersofthem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='givencoursesandthesemestersofthem',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_courses', to='courses.semester'),
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
