# Generated by Django 5.1.1 on 2024-10-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_academicdream_curriculum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdream',
            name='CurriculumCourseSemester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semcor_academic_dream', to='courses.curriculumcoursesemester'),
        ),
        migrations.AlterField(
            model_name='academicdream',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_dream', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
