# Generated by Django 5.1.1 on 2024-10-03 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_delete_academicdream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, default=-1)),
                ('curriculum_course_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semcor_academic_dream', to='courses.curriculumcoursesemester')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_academic_dream', to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_dream', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
