# Generated by Django 5.1.1 on 2024-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_sectionpacket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpacket',
            name='section',
        ),
        migrations.AddField(
            model_name='sectionpacket',
            name='section',
            field=models.ManyToManyField(to='courses.section'),
        ),
    ]
