# Generated by Django 5.1.1 on 2024-10-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_sectionpacket_section_sectionpacket_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdream',
            name='section',
        ),
        migrations.AddField(
            model_name='academicdream',
            name='section_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_academic_dream', to='courses.sectionpacket'),
        ),
    ]
