# Generated by Django 5.1 on 2024-08-27 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('course_code', models.CharField(max_length=200)),
                ('max_credit_points', models.CharField(max_length=10)),
                ('students_credit_point', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='ENG', max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('schedule', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=50)),
                ('building_name', models.CharField(choices=[('ENG', 'FACULTY OF ENGINEERING'), ('LAW', 'FACULTY OF LAW'), ('MED', 'FACULTY OF MEDICINE'), ('LANG', 'FACULTY OF LANGUAGE'), ('LIT', 'FACULTY OF LITERATURE'), ('SCI', 'FACULTY OF SCIENCE')], max_length=100)),
                ('floor_name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.section'),
        ),
        migrations.AddField(
            model_name='course',
            name='offered_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_for_semester', to='courses.semester'),
        ),
    ]
