# Generated by Django 5.1 on 2024-08-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_it_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(default='Not registered', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.section'),
        ),
    ]
