# Generated by Django 5.1 on 2024-08-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_it_offered_alter_course_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_credit_point',
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_for_semester', to='courses.semester'),
        ),
    ]
