# Generated by Django 5.1 on 2024-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_students_credit_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
