# Generated by Django 5.1 on 2024-08-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offered_semester',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.section'),
        ),
    ]
